#include "stm32f0xx.h"

void CLOCK_config_48Mhz(void){
	if((RCC->CR & RCC_CR_HSION)==0){RCC->CR|=RCC_CR_HSION;}
	while((RCC->CR & RCC_CR_HSIRDY)==0);
	RCC->CFGR|=RCC_CFGR_PLLSRC_HSI_DIV2;
	RCC->CFGR|=RCC_CFGR_PLLMUL12;
	if((RCC->CFGR & RCC_CFGR_SWS)!=RCC_CFGR_SWS_PLL){RCC->CFGR|=RCC_CFGR_SW_PLL;}
	RCC->CR|=RCC_CR_PLLON;
	while((RCC->CR & RCC_CR_PLLRDY)==0);
}

void LED(uint8_t state){
	RCC->AHBENR|=RCC_AHBENR_GPIOAEN;
	GPIOA->MODER|=GPIO_MODER_MODER3_0;
	if(state==0){GPIOA->ODR&=~GPIO_ODR_3;}
	else{GPIOA->ODR|=GPIO_ODR_3;}
}

void ENABLE_oled(void){
	RCC->AHBENR|=RCC_AHBENR_GPIOAEN;
	GPIOA->MODER|=GPIO_MODER_MODER0_0;
	GPIOA->ODR|=GPIO_ODR_0;
}
